export const inventory = {
  medications: [
    {
      id: '1',
      name: 'Paracetamol',
      genericName: 'Acetaminophen',
      category: 'Analgesic',
      dosageForm: 'Tablet',
      strengths: ['500mg', '650mg'],
      manufacturer: 'Generic Co',
      stock: 500,
      reorderLevel: 100,
      unit: 'tablets',
      expiryDate: '2025-12-31',
    },
    {
      id: '2',
      name: 'Amoxicillin',
      genericName: 'Amoxicillin',
      category: 'Antibiotic',
      dosageForm: 'Capsule',
      strengths: ['250mg', '500mg'],
      manufacturer: 'Pharma Inc',
      stock: 50,
      reorderLevel: 100,
      unit: 'capsules',
      expiryDate: '2025-06-30',
    },
    {
      id: '3',
      name: 'Metformin',
      genericName: 'Metformin Hydrochloride',
      category: 'Antidiabetic',
      dosageForm: 'Tablet',
      strengths: ['500mg', '850mg', '1000mg'],
      manufacturer: 'Diabetes Care Ltd',
      stock: 200,
      reorderLevel: 150,
      unit: 'tablets',
      expiryDate: '2024-12-31',
    },
  ]
};

// Mock procedures aligned with FHIR CodeableConcept fields
export const procedures = [
  {
    name: "Wound Toilet & Dressing",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "97602",
    codingDisplay: "Removal of devitalized tissue, non-selective, without anesthesia",
    category: "Nursing",
    defaultPrice: 50.0,
    notes: "Simple dressing change",
  },
  {
    name: "Suturing (Simple) up to 5 cm",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "12001",
    codingDisplay: "Simple repair superficial wounds; 2.5 cm or less",
    category: "Procedure",
    defaultPrice: 120.0,
    notes: "Clinic simple closure",
  },
  {
    name: "Incision & Drainage (Abscess)",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "10060",
    codingDisplay: "I&D of abscess (simple or single)",
    category: "Procedure",
    defaultPrice: 150.0,
    notes: "Local anesthesia",
  },
  {
    name: "Intramuscular Injection",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "96372",
    codingDisplay: "Therapeutic, prophylactic, or diagnostic injection, IM/SC",
    category: "Injection",
    defaultPrice: 30.0,
    notes: "Excludes drug cost",
  },
  {
    name: "Nebulization Therapy",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "94640",
    codingDisplay: "Pressurized or nonpressurized inhalation treatment",
    category: "Respiratory",
    defaultPrice: 40.0,
  },
  {
    name: "12‑lead ECG with Interpretation",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "93000",
    codingDisplay: "ECG routine 12 leads with interpretation and report",
    category: "Diagnostics",
    defaultPrice: 35.0,
  },
  {
    name: "Ear Wax Removal (Irrigation)",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "69209",
    codingDisplay: "Removal of impacted cerumen by irrigation/lavage, unilateral",
    category: "ENT",
    defaultPrice: 45.0,
  },
  {
    name: "Foreign Body Removal (Skin, Simple)",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "10120",
    codingDisplay: "Incision and removal of foreign body, subcutaneous; simple",
    category: "Procedure",
    defaultPrice: 80.0,
  },
  {
    name: "IV Cannulation",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "36000",
    codingDisplay: "Introduction of needle or intracatheter, vein",
    category: "Procedure",
    defaultPrice: 35.0,
  },
  {
    name: "Phlebotomy (Venipuncture)",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "36415",
    codingDisplay: "Collection of venous blood by venipuncture",
    category: "Laboratory",
    defaultPrice: 12.0,
  },
  {
    name: "Urine Dipstick (POC)",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "81002",
    codingDisplay: "Urinalysis by dip stick, non‑automated, without microscopy",
    category: "POCT",
    defaultPrice: 10.0,
  },
  {
    name: "Suture Removal (Follow‑up)",
    codingSystem: "http://www.ama-assn.org/go/cpt",
    codingCode: "15850",
    codingDisplay: "Removal of sutures under anesthesia (placeholder)",
    category: "Procedure",
    defaultPrice: 25.0,
    notes: "Verify local coding; may be bundled post‑op",
  },
];
